### ISSUE TITLE
Call to a member function getDefaultValue() on a non-object

### ISSUE THREAD

**Issue by pvsureshmca** [Roomify/bat#16]
I got below error when admin tries to add the property. Kindly help me how to fix this issue

Fatal error: Call to a member function getDefaultValue() on a non-object in /var/www/html/seken-dev/sites/all/vendor/roomify/bat/src/Calendar/AbstractCalendar.php on line 251

**Comment by ArberD** [comment]
@pvsureshmca looks like your issue is related to the way you are using BAT not the package itself.

**Comment by acrollet** [comment]
Yes, please open an issue here if you are using RfA: https://github.com/roomify/rfa
