### ISSUE TITLE
How I search 

### ISSUE THREAD

**Issue by anhskohbo** [Roomify/bat#19]
Hi, I'm writing a Hotel Booking for WordPress. And thanks god I found this package. Seem it's help me so much.

But my idea is when user create a room, it's always available to book.

I wonder if BAT can do `getMatchingUnits` without pass `events`?

**Comment by acrollet** [comment]
Hi @anhskohbo,

BAT is quite agnostic about how you use it - when you create a Unit, (room) you pass a default state to it. If you consider that state to be 'available to book', you can just look for matching units in that state.

good luck!
