### ISSUE TITLE
BAT Calendar Reference activation problem

### ISSUE THREAD

**Issue by simmonspaul** [Roomify/bat#2]
I am playing around with drupal booking and availability functionality and of course you guys are leading the way...

I encountered three issues in getting the Bat project installed.
The first two are not strictly Bat issues but others might be assisted by improving the documentation.

#1 Documentation - If installing via Composer one must allow Development level stability
I had difficulties installing the BAT php library using the instructions:
composer require roomify/bat
Effectively, composer could not find a "stable" version to install.
I had to change my composer.json file to allow dev versions:
"minimum-stability": "dev",
    "require": {
        "drush/drush": "dev-master",
        "roomify/bat": "@dev"
     }
}

#2 Documentation - Other required Drupal modules
I am on Drupal 7.41 and had an issue when enabling the modules.
First off there were a couple of dependencies that had to be installed:
search_api, facetapi, fullcalendar, views_megarow, views_bulk_operations

#3 Issue enabling BAT Calendar Reference.
I got errors indicating reference problems in the following file. 
sites/all/modules/bat/modules/bat_calendar_reference/bat_calendar_reference.module

There were three errors in total. Each time I commented out the seemingly offensive code as follows.
I have not yet properly used the project to understand the implications of my hack. The module has been sucessfully enabled.

I commented out the problematic lines to force it to enable.
lines 386 - 390
//  if (is_array($field['settings']['referenceable_unit_types'])) {
//    if (!empty(array_filter($field['settings']['referenceable_unit_types']))) {
//      $query->condition('u.type_id', array_filter($field['settings']['referenceable_unit_types']), 'IN');
//    }
//  }

line 485 - 489
//  if (is_array($field['settings']['referenceable_event_types'])) {
//    if (!empty(array_filter($field['settings']['referenceable_event_types']))) {
//      $query->condition('u.id', array_filter($field['settings']['referenceable_event_types']), 'IN');
//    }
//  }

lines 579 - 581
  if (is_array($field['settings']['referenceable_event_types'])) {
//    if (!empty(array_filter($field['settings']['referenceable_event_types']))) {
  //    $query->condition('u.type_id', array_filter($field['settings']['referenceable_event_types']), 'IN');
 //   }
  }

**Comment by acrollet** [comment]
Hi @simmonspaul,

thanks for the feedback. I've updated the README to mention composer's minimum-stability setting. We do also mention all required modules in the README, but would welcome any suggestions to improve/clarify it.

Re: bat_calendar_reference - the project is very much in active development, can you re-install with the latest commits of bat_drupal and bat_api (7.x-2.x) and see if the problems are still present? If so, it would be helpful to know what the exact errors you receive are.

**Comment by simmonspaul** [comment]
Thank you.

#1 thanks

#3 To clarify, my environment was setup with bat (1.0.0-alpha), bat_drupal (7.x-1.x-dev) and bat_api (7.x-1.0). I will retest using 7.x-2.x as advised.

The precise error I was getting was:
Fatal error: Can't use function return value in write context in /home2/scoundre/git/pstaging/sites/all/modules/bat/modules/bat_calendar_reference/bat_calendar_reference.module on line 387

same error lines 486 and 579

#2 k, I remember actually going into the Bat module README.md file itself and skimming the content and seeing the required modules section - so apologies I was slightly brain dead. 

What is going on is we have a drupal module/project named BAT (which is where I started from and the install process). The module is installed in a directory called bat. However that underlying code is referred to as bat_drupal in github. I didn't know bat_drupal existed.

So I was making an error to read the BAT github page (that is described as the README.md) after installing the BAT module and it did not have a section on required modules.

I don't think I will be the only one that gets confused.

So if I had known what I know now, #2 and #3 should have been raised against bat_drupal.



I should have been looking at the bat_drupal in github.

I don't think I will be the last one to be confused

**Comment by acrollet** [comment]
Hi @simmonspaul,

it is true that there is a lot going on - I myself didn't twig about this issue being on the bat queue vs the bat_drupal queue. We do give a link to the readme of bat_drupal when enabling the module, and I've added a link from the drupal.org module page. Definitely open to suggestions on clarifying these matters. If you have further trouble please feel free to raise an issue in the drupal.org queue or the bat_drupal github project.
