### ISSUE TITLE
Why forced Event value is integer.

### ISSUE THREAD

**Issue by anhskohbo** [Roomify/bat#20]
I still don't understand all the concepts of BAT ('cause my English is not good so much). 

As you say "Events define what value a unit has for a given time period". It's could be **Price** of **Room** in a time period.

But I see in this line: https://github.com/Roomify/bat/blob/master/src/Event/AbstractEvent.php#L65, value of Event forced is integer type. What if I have a float number in this case:

In: 05/03/2017-10/03/2017 Price of Room is: 99.99$/night?

BTW, thanks for great project!

**Comment by acrollet** [comment]
Hi @anhskohbo you would simply set the price in the smallest unit of the currency, i.e. 9999 for USD99.99
