### ISSUE TITLE
Change event granularity to smaller increments of time

### ISSUE THREAD

**Issue by jfrisina** [Roomify/bat#30]
Currently, the event granularity is either Daily or Hourly. For meeting rooms, it would be helpful to have greater control over the granularity, such as adding 15 minute increments for setup time (total meeting time: 1 hour and 15 minutes), or 30 minutes for shorter meetings.

**Comment by acrollet** [comment]
@jfrisina I believe you're perhaps looking at the BAT drupal module? This is a pure php library that goes down to minute granularity.
